import munit.FunSuite

class Day07Spec extends FunSuite:
  val exampleInput =
    """
    |.......S.......
    |...............
    |.......^.......
    |...............
    |......^.^......
    |...............
    |.....^.^.^.....
    |...............
    |....^.^...^....
    |...............
    |...^.^...^.^...
    |...............
    |..^...^.....^..
    |...............
    |.^.^.^.^.^...^.
    |...............
    """.stripMargin.trim

  test("Day 7 - Part 1 Example") {
    assertEquals(Day07.part1(exampleInput), 21)
  }

  test("Day 7 - Part 2 Example") {
    assertEquals(Day07.part2(exampleInput), 40)
  }
